name: deploy

on:
  workflow_call:
  
jobs:
  my-job-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: print
        run : echo github.event_name

      - name: print
        run : echo ${{ github.event_name }} 
