name: fetchcore_pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  echo_helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1
        run: echo "Hello World!"
      - name: my-step2
        run: echo ${{ github.event.issue.pull_request}}
         
 

  deploy:
    needs: [echo_helloworld]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
